Library/Controllers/BooksController.cs
using Library.DataBase.Entities;
using Library.ViewModels.Books;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using Library.Domain.Interfaces;
using AutoMapper;
using System.Collections.Generic;

namespace Library.Controllers
{
    public class BooksController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IRepository<Book> _repository;

        public BooksController(IRepository<Book> repository, IMapper mapper)
        {
            _repository = repository;
            _mapper = mapper;
        }

        [Route("Books/List/{genre}")]
        public async Task<IActionResult> List(int genre)
        {
            var books = await _repository.GetAll()
                .OrderBy(x => x.Id).Where(c => c.GenreId == genre).ToListAsync();
            var model = _mapper.Map<List<AllBookListViewModel>>(books);

            return View(model);
        }

        public async Task<IActionResult> Index(string searchString, string category)
        {
            var books = category switch
            {
                "name" => _repository.GetAll().Where(c => c.Name.Contains(searchString)),
                "author" => _repository.GetAll().Where(c => c.Author.Contains(searchString)),
                "publisher" => _repository.GetAll().Where(c => c.Publisher.Contains(searchString)),
                _ => _repository.GetAll()
            };
            var book = await books.OrderBy(x => x.Id).ToListAsync();
            var model = _mapper.Map<List<AllBookListViewModel>>(books);
            return View(model);
        }

        public async Task<IActionResult> CurrentBook(int bookId)
        {
            var book = await _repository.GetByIdAsync(bookId);
            var model = _mapper.Map<AllBookListViewModel>(book);
            return View(model);
        }
    }
}

Library/Controllers/RolesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Library.DataBase.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Library.ViewModels.Roles;
using Library.ViewModels.Users;
using AutoMapper;

namespace Library.Controllers
{
    [Authorize(Roles = "admin")]
    public class RolesController : Controller
    {
        private readonly IMapper _mapper;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<User> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager, IMapper mapper)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.OrderBy(x => x.Id).ToListAsync();
            var model = _mapper.Map<List<AllRolesListViewModel>>(roles);
            return View(model);
        }

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                var result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> UserList()
        {
            var users = await _userManager.Users.OrderBy(x => x.Id).ToListAsync();
            var model = _mapper.Map<List<AllUsersListViewModel>>(users);
            return View(model);
        }

        public async Task<IActionResult> Edit(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            var userRoles = await _userManager.GetRolesAsync(user);
            var allRoles = _roleManager.Roles.ToList();
            var model = new ChangeRoleViewModel
            {
                UserId = user.Id,
                UserEmail = user.Email,
                UserRoles = userRoles,
                AllRoles = allRoles
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var addedRoles = roles.Except(userRoles);
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" />
    <link href="~/css/customElementStyle.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark" style="background-color:darkmagenta">
            <a class="navbar-brand nav-item text-light" href="/">Библиотека</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav mr-auto">
                    <select onchange="window.location.href = this.options[this.selectedIndex].value">
                        <option value="" hidden>Жанры</option>
                        <option value="/Books/List/1">Фантастика</option>
                        <option value="/Books/List/4">Романы</option>
                        <option value="/Books/List/2">Детектив</option>
                        <option value="/Books/List/5">Поэзия</option>
                    </select>
                    <form asp-controller="Books" asp-action="Index">
                        <p class="text-light">
                            <input type="text" placeholder="Искать здесь..." name="searchString" />
                            <input type="radio" name="category" value="name" checked />
                            <label>По названию</label>
                            <input type="radio" name="category" value="author" />
                            <label>По автору</label>
                            <input type="radio" name="category" value="publisher" />
                            <label>По издателю</label>
                            <input type="submit" value="Поиск" />
                        </p>
                    </form>
                </div>
                <form class="form-inline mt-2 mt-md-0">
                    @if (User.Identity.IsAuthenticated)
                    {
                        @if (User.IsInRole("admin"))
                        {
                            <a class="navbar-brand nav-item text-light" asp-controller="Users" asp-action="Index">Пользователи</a>
                            <a class="navbar-brand nav-item text-light" asp-controller="Roles" asp-action="Index">Роли</a>
                        }
                        else if (User.IsInRole("librarian"))
                        {
                            <a class="navbar-brand nav-item text-light" asp-controller="Librarian" asp-action="AllOrders">Заказы</a>
                            <a class="navbar-brand nav-item text-light" asp-controller="Librarian" asp-action="Index">Список книг</a>
                        }
                        @if (User.IsInRole("user"))
                        {
                            <a class="navbar-brand nav-item text-light" asp-controller="Order" asp-action="MyOrders">Мои книги</a>

                        }
                        <a class="navbar-brand" style="font-style:italic"><b>@User.Identity.Name.Substring(0, User.Identity.Name.LastIndexOf('@'))</b></a>
                        <form method="post" asp-controller="Account" asp-action="LogOut">
                            <button type="submit" class="btn btn-outline-danger">
                                Выйти
                            </button>
                        </form>
                    }
                    else
                    {
                        <a class="btn btn-outline-light" asp-controller="Account" asp-action="Login">Войти</a>
                        <a class="btn btn-outline-light" asp-controller="Account" asp-action="Register">Регистрация</a>
                    }
                </form>
            </div>
        </nav>
    </header>
    <div class="container" mt-5>
        @RenderBody()
    </div>
    <script scr="~/js/bootstrap.min.js"></script>
</body>
</html>